version: '2'
services:
  emby:
    image: emby/embyserver
    container_name: emby
    ports:
     - "8096:8096/tcp"
     - "8920:8920/tcp"
     - "7359:7359/udp"
     - "1900:1900/udp"
    volumes:
     - ./emby-config:/config
     - ./video:/media/video
     - ./downloads:/media/downloads
    restart: unless-stopped
