version: '2'
services:
  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: "host"
    ports:
     - "8096:8096/tcp"
     - "8920:8920/tcp"
     - "7359:7359/udp"
     - "1900:1900/udp"
    volumes:
     - ./emby-config:/config
     - ./video:/media/video
     - ./downloads:/media/downloads
    devices:
     - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - "9091:9091/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    volumes:
      - ./transmission-config:/config
      - ./transmission-downloads:/downloads
    environment:
      - TZ=Europe/Vilnius
    restart: unless-stopped
