version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    depends_on:
      - mqtt
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant-config:/config
    environment:
      - TZ=Europe/Vilnius
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    depends_on:
      - homeassistant
    ports:
      - 5050:5050
    volumes:
      - ./appdaemon:/conf
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
