version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    depends_on:
      - mqtt
    ports:
      - "987:987/udp"
      - 997:997
      - 8123:8123
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./homeassistant-config:/config
    environment:
      - TZ=Europe/Vilnius
    privileged: true
    restart: unless-stopped
    network_mode: "host"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    depends_on:
      - homeassistant
    ports:
      - 5050:5050
    volumes:
      - ./appdaemon:/conf
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nodered:/data
    environment:
      - TZ=Europe/Vilnius
    restart: unless-stopped

