---
version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.0.0
    container_name: prometheus
    volumes:
      - ./prometheus-config/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=800h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    depends_on:
      - prometheus_config_hook
    labels:
      org.label-schema.group: "monitoring"
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes: 
      - ./prometheus-config/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/alertmanager.yml'
      - '-storage.path=/alertmanager'
      - '-web.external-url=http://zx:9093'
    restart: unless-stopped
    ports:
      - "9093:9093"
    networks:
      - monitor-net
    depends_on:
      - prometheus_config_hook
    labels:
      org.label-schema.group: "monitoring"

  unsee:
    image: cloudflare/unsee:latest
    container_name: unsee
    environment:
      - ALERTMANAGER_URIS=default:http://alertmanager:9093
    restart: unless-stopped
    ports:
      - "9099:8080"
    networks:
      - monitor-net
    depends_on:
      - alertmanager
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

