groups:
- name: host.rules
  rules:
  # linux
  - alert: high_cpu_load
    expr: (100 - (avg by (instance) (irate(node_cpu{name="node-exporter",mode="idle"}[5m])) * 100)) > 90
    for: 300s
    labels:
      severity: warning
    annotations:
      description: Host is under high load, the cpu load 5m is at {{ $value}} %.
        Reported by instance {{ $labels.instance }} of job {{ $labels.job }}.
      summary: Server under high load
  # linux
  - alert: high_memory_load
    expr: (sum by (instance)(node_memory_MemTotal) - sum by (instance)(node_memory_MemFree + node_memory_Buffers + node_memory_Cached))
      / sum by (instance)(node_memory_MemTotal) * 100 > 85
    for: 300s
    labels:
      severity: warning
    annotations:
      description: Host memory usage is {{ humanize $value}}%. Reported by
        instance {{ $labels.instance }} of job {{ $labels.job }}.
      summary: Server memory is almost full
  # linux
  - alert: low_free_space
    expr: (node_filesystem_size - node_filesystem_free) / node_filesystem_size * 100 > 95
    for: 30s
    labels:
      severity: warning
    annotations:
      description: Host storage usage is {{ humanize $value}}%. Reported by
        instance {{ $labels.instance }} of job {{ $labels.job }}.
      summary: Server storage is almost full
