global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'home-monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "*.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: therm-exporter
    static_configs:
    - targets: ['pi:8000']
      labels:
        service: therm
        instance: pi

  - job_name: weather-exporter
    static_configs:
    - targets: ['openweathermap:9520']
      labels:
        service: weather
        instance: zx

  - job_name: cadvisor-exporter
    static_configs:
    - targets: ['cadvisor:18080']
      labels:
        service: cadvisor
        instance: zx

  - job_name: node-exporter
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        service: node
        instance: zx

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
